### ISSUE TITLE
Code generation for each protocol version may not scale

### ISSUE THREAD

**Issue by ccapitalK** [sebosp/s2protocol-rs#10]
I don't think code generation for each different protocol version is a good approach, it appears to cause extremely long compile times and massive binary sizes, and I don't think you would gain that much in terms of performance. It might make sense to just load it into a Serde deserializable struct from a provide json file at run time, and read from that struct in the replay reading code? I would be surprised if that resulted in that much run-time overhead.

On an unrelated note, this is an incredibly cool project, great job! You might want to show it off to the SC2 AI Arena discord, they seem like might would appreciate a standalone viewer for SC2 replays,

**Comment by sebosp** [comment]
Thanks for the feedback! My first thought was to follow the same structure as the original Blizzard/s2protocol in which they have per protocol versions, thus far in the generated modules the code is the same, I'm concerned if in between versions the number of bits/bytes could change for specific fields.
I agree that maybe using `syn` and `quote` crates would make for smaller compile times and less tedious, I guess the first step was to try to understand how the events are related to each other and since now it seems to be constistent understanding of bit_packed and byte_aligned data structures then it should be possible to make something easier to work with.
I will give it some thought because the current code generation code is some code I don't ever want to have to read again, it's by far the ugliest thing I've built :)
If you have a good idea on how to start the Serde that would be amazing, it would be so easy to read and understand!

**Comment by sebosp** [comment]
I have been giving it more thought and I think there are a couple of things that can be done:
1.  I think we can read all the blizzard s2protocol version definition jsons (or a "recent" subset of them) and compare if a struct has changed or not and is re-usable between versions. Something like:
```rust
pub mod versionless {
    pub struct AlwaysTheSame;
    pub struct ChangingStruct;
}
pub mod version87702 {
   use versionless::AlwaysTheSame;
   pub struct ChangingStruct;
   pub struct OnlyOnThisVersion;
}
```

2. I'm not checking yet if a struct is actually used, if it happens to be just defined because it's in the protocol definition or not, tho I think that this would be caught by clippy-lints (altho clippy lints right now show a million issues).

**Comment by sebosp** [comment]
I played a bit over the past couple of weeks with different ways to re-use the types. The new 2.0.0 reuses as much as possible types all in reference to the protocol 87702 that was used initially to build the PoC.
